// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI agent that detects the severity of symptoms and suggests seeking immediate medical attention if necessary.
 *
 * - detectSeverity - A function that takes symptom descriptions and flags potentially serious conditions.
 * - DetectSeverityInput - The input type for the detectSeverity function.
 * - DetectSeverityOutput - The return type for the detectSeverity function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectSeverityInputSchema = z.object({
  symptoms: z
    .string()
    .describe('A description of the symptoms experienced by the user.'),
  photoDataUri: z
    .string()
    .optional()
    .describe(
      "An optional photo of the symptom, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type DetectSeverityInput = z.infer<typeof DetectSeverityInputSchema>;

const DetectSeverityOutputSchema = z.object({
  isSerious: z
    .boolean()
    .describe(
      'Whether or not the described symptoms indicate a potentially serious condition that requires immediate medical attention.'
    ),
  explanation: z
    .string()
    .describe(
      'A clear and concise explanation of why the symptoms are considered serious, or why they are not.'
    ),
  suggestImmediateAction: z
    .boolean()
    .describe(
      'Whether or not the user should seek immediate medical attention based on the symptoms.'
    ),
});
export type DetectSeverityOutput = z.infer<typeof DetectSeverityOutputSchema>;

export async function detectSeverity(input: DetectSeverityInput): Promise<DetectSeverityOutput> {
  return detectSeverityFlow(input);
}

const detectSeverityPrompt = ai.definePrompt({
  name: 'detectSeverityPrompt',
  input: {schema: DetectSeverityInputSchema},
  output: {schema: DetectSeverityOutputSchema},
  prompt: `You are a medical expert tasked with analyzing a patient's described symptoms to determine if they indicate a potentially serious medical condition requiring immediate attention.

  Based on the following description of symptoms:
  """{{symptoms}}"""

  {{#if photoDataUri}}
  Also consider the attached photo for your analysis:
  {{media url=photoDataUri}}
  {{/if}}

  Determine if the symptoms suggest a serious condition. Set the isSerious field to true if they do, and false if they do not.

  Provide a brief explanation in the explanation field for your determination. Explain your reasoning to the user.

  If the symptoms are serious, set the suggestImmediateAction field to true. Otherwise, set it to false.
  `,
});

const detectSeverityFlow = ai.defineFlow(
  {
    name: 'detectSeverityFlow',
    inputSchema: DetectSeverityInputSchema,
    outputSchema: DetectSeverityOutputSchema,
  },
  async input => {
    const {output} = await detectSeverityPrompt(input);
    return output!;
  }
);
